return {
    -- Table of overrides/changes to the vscode theme
    GitSignsAdd = { fg = "#487e02" },
    GitSignsChange = { fg = "#1b81a8" },
    NeoTreeGitAdded = { fg = "#73c991" },
    NeoTreeGitDeleted = { fg = "#c74e39" },
    NeoTreeGitIgnored = { fg = "#8c8c8c" },
    NeoTreeGitModified = { fg = "#e2c08d" },
    NeoTreeGitUnstaged = { fg = "#e2c08d" },
    NeoTreeGitUntracked = { fg = "#73c991" },
    NeoTreeGitStaged = { fg = "#e2c08d" },
    NeoTreeTitleBar = { fg = "#d4d4d4", bg = "#444444" },
    NeoTreeTabSeparatorActive = { fg = "#1E1E1E", bg = "#1E1E1E" },
    NeoTreeTabSeparatorInactive = { fg = "#141414", bg = "#141414" },
    NeoTreeDirectoryIcon = { fg = "#569CD6" },
    NeoTreeDirectoryName = { fg = "#569CD6" },
    TabLineFill = { fg = "#141414", bg = "#141414" },
    LineNr = { fg = "#858585" },
    CursorLineNr = { fg = "#c6c6c6" },
    CursorLine = { bg = "#282828" },
    CursorColumn = { bg = "#282828" },
    GitBlameText = { fg = "#707070", bg = "#282828" },
    IncRenameText = { bg = "#613214" },
    -- SpellBad = { underline = false, fg = "#F44747" },
    SpellCap = { undercurl = true, fg = "#569CD6", sp = "#569CD6" },
    SpellRare = { undercurl = true, fg = "#DCDCAA", sp = "#DCDCAA" },
    ["@comment.documentation"] = { fg = "#569cd6" },
    DiffviewDiffDeleteDim = { fg = "#414141" },
    DiffText = { bg = "#185f7a" },
    DiffChange = { bg = "#153947" },
    LspSignatureActiveParameter = { fg = "#2aaaff" },
    TreesitterContext = { bg = "#404040" },
    NeorgContext = { link = "TreesitterContext" },
    DiagnosticUnnecessary = { fg = "#8D8D8D" },
    NvimDapVirtualText = { fg = "#707070" },
    NvimDapVirtualTextChanged = { link = "DiagnosticVirtualTextInfo" },
    LazyButton = { fg = "#D4D4D4", bg = "#404040" },
    LazyButtonActive = { bg = "#264F78", bold = true },
    LazyH1 = { fg = "#000000", bg = "#2aaaff", bold = true },
    LazySpecial = { fg = "#569CD6" },
    MasonHeader = { link = "LazyH1" },
    MasonHeaderSecondary = { link = "MasonHeaderSecondary" },
    MasonHighlightBlock = { bg = "#264F78" },
    MasonHighlightBlockSecondary = { link = "MasonHighlightBlockSecondary" },
    MasonHighlightBlockBold = { link = "LazyButtonActive" },
    MasonHighlightBlockBoldSecondary = { link = "MasonHighlightBlockBold" },
    MasonMutedBlock = { link = "LazyButton" },
    MasonHighlight = { link = "DiagnosticInfo" },
    MasonHighlightSecondary = { link = "MasonHighlight" },
    MasonMuted = { link = "DiagnosticError" },
    -- Handles both hover text and floating windows' background. Hover text looks better with it, but floating windows without borders don't
    -- By default links to Pmenu, so set floating windows without borders' background highlight to it and override it for the rest
    NormalFloat = { link = "Normal" },
    LazyNormal = { link = "Pmenu" },
    MasonNormal = { link = "Pmenu" },
    WhichKeyFloat = { link = "Pmenu" },
    MultiCursor = { link = "Visual" },
    MultiCursorMain = { link = "Visual" },
    SpecialChar = { link = "Special" },
    MatchParen = { fg = "#11d116" },
    ["@punctuation.special"] = { fg = "#569CD6" },
    StatusLine = { fg = "#626262", bg = "#242424" },
    FloatBorder = { link = "LspInfoBorder" },
    NullLsInfoBorder = { link = "FloatBorder" },
}
