return {
    -- a table of overrides/changes to the vscode theme
    GitSignsAdd = { fg = "#487e02" },
    GitSignsChange = { fg = "#1b81a8" },
    NeoTreeGitAdded = { fg = "#73c991" },
    NeoTreeGitDeleted = { fg = "#c74e39" },
    NeoTreeGitIgnored = { fg = "#8c8c8c" },
    NeoTreeGitModified = { fg = "#e2c08d" },
    NeoTreeGitUnstaged = { fg = "#e2c08d" },
    NeoTreeGitUntracked = { fg = "#73c991" },
    NeoTreeGitStaged = { fg = "#e2c08d" },
    NeoTreeTitleBar = { fg = "#d4d4d4", bg = "#444444" },
    LineNr = { fg = "#858585", bg = "#1E1E1E" },
    CursorLineNr = { fg = "#c6c6c6", bg = "#1E1E1E" },
    CursorLine = { bg = "#282828" },
    CursorColumn = { bg = "#282828" },
    GitBlameText = { fg = "#707070", bg = "#282828" },
    IncRenameText = { bg = "#613214" },
    SpellBad = { underline = false, fg = "#F44747" },
    SpellCap = { underline = true, fg = "#569CD6" },
    SpellRare = { underline = true, fg = "#DCDCAA" },
    ["@comment.documentation"] = { fg = "#569cd6" },
    DiffviewDiffDelete = { fg = "#414141" },
    DiffText = { bg = "#185f7a" },
    DiffChange = { bg = "#153947" },
    LspSignatureActiveParameter = { fg = "#2aaaff" },
    -- Handles both hover text and Lazy/Mason background. Hover text looks better with it, but Lazy/Mason don't as they don't have borders
    -- NormalFloat = { fg = "#d4d4d4", bg = "#1E1E1E" },
    TreesitterContextBottom = { underline = true, sp = "#444444" },
}
