-- Custom icons to use. Commented lines use the default
return {
    -- ActiveLSP = "",
    -- ActiveTS = "",
    -- ArrowLeft = "",
    -- ArrowRight = "",
    -- BufferClose = "󰅖",
    -- DapBreakpoint = "",
    -- DapBreakpointCondition = "",
    -- DapBreakpointRejected = "",
    DapLogPoint = "",
    DapStopped = "",
    -- DefaultFile = "󰈙",
    -- Diagnostic = "󰒡",
    -- DiagnosticError = "",
    -- DiagnosticHint = "󰌵",
    DiagnosticInfo = " ",
    -- DiagnosticWarn = "",
    Ellipsis = "",
    -- FileModified = "",
    -- FileReadOnly = "",
    -- FoldClosed = "",
    -- FoldOpened = "",
    -- FoldSeparator = " ",
    -- FolderClosed = "",
    -- FolderEmpty = "",
    -- FolderOpen = "",
    -- Git = "󰊢",
    -- GitAdd = "",
    -- GitBranch = "",
    -- GitChange = "",
    -- GitConflict = "",
    -- GitDelete = "",
    -- GitIgnored = "◌",
    -- GitRenamed = "➜",
    GitStaged = "",
    GitUnstaged = "",
    GitUntracked = "󰓎",
    -- LSPLoaded = "",
    -- LSPLoading1 = "",
    -- LSPLoading2 = "󰀚",
    -- LSPLoading3 = "",
    -- MacroRecording = "",
    -- Paste = "󰅌",
    ScrollText = "",
    -- Search = "",
    -- Selected = "❯",
    -- Spellcheck = "󰓆",
    -- TabClose = "󰅙",
    VimIcon = "",
    -- stylua: ignore
    ---@format disable-next
    lsp = {
        array         = { glyph = "󰅪", hl = "@variable"                     },
        boolean       = { glyph = "󰨙", hl = "@variable"                     },
        class         = { glyph = "󰠱", hl = "CmpItemKindConstructor"        },
        color         = { glyph = "󰏘", hl = "cssColor"                      },
        constant      = { glyph = "󰏿", hl = "@constant"                     },
        constructor   = { glyph = "", hl = "CmpItemKindConstructor"        },
        enum          = { glyph = "", hl = "@variable"                     },
        enummember    = { glyph = "", hl = "@variable"                     },
        event         = { glyph = "", hl = "@constant"                     },
        field         = { glyph = "󰜢", hl = "@variable"                     },
        file          = { glyph = "󰈙", hl = "@markup.link"                  },
        folder        = { glyph = "󰉋", hl = "@markup.link"                  },
        ['function']  = { glyph = "󰊕", hl = "@keyword"                      },
        interface     = { glyph = "", hl = "@variable"                     },
        key           = { glyph = "󰌆", hl = "@variable"                     },
        keyword       = { glyph = "󰌋", hl = "MiniIconsGrey"                 },
        method        = { glyph = "", hl = "MiniIconsPurple"               },
        module        = { glyph = "", hl = "@module"                       },
        namespace     = { glyph = "", hl = "@module"                       },
        null          = { glyph = "", hl = "MiniIconsGrey"                 },
        number        = { glyph = "󰎠", hl = "@variable"                     },
        object        = { glyph = "󰀚", hl = "@variable"                     },
        operator      = { glyph = "󰆕", hl = "MiniIconsGrey"                 },
        package       = { glyph = "󰏗", hl = "@module"                       },
        property      = { glyph = "", hl = "@property"                     },
        reference     = { glyph = "󰈇", hl = "@variable.parameter.reference" },
        snippet       = { glyph = "", hl = "MiniIconsGrey"                 },
        string        = { glyph = "󰀬", hl = "@variable"                     },
        struct        = { glyph = "󰙅", hl = "@structure"                    },
        text          = { glyph = "󰀬", hl = "@variable"                     },
        typeparameter = { glyph = "󰊄", hl = "@type"                         },
        unit          = { glyph = "󰑭", hl = "MiniIconsGrey"                 },
        value         = { glyph = "󰎠", hl = "@variable"                     },
        variable      = { glyph = "󰀫", hl = "@variable"                     },
    },
}
