--- Block of groups of snippet specs. The key is the name of the group
---@alias SnippetBlock {[string]: SnippetGroup}

--- Format: `cmds[num_params][group_name][create_autosnippet] = SnippetSpecs`
---@class Cmds
---@field [1] SnippetBlock Commands with no arguments
---@field [2] SnippetBlock Commands with 1 argument
---@field [3] SnippetBlock Commands with 2 arguments

-- stylua: ignore
return {
    ---@type Cmds
    cmds = {
        {
            delimiters = {
                [false] = {
                    -- "lparen", "rparen",
                    -- "lbrack", "rbrack",
                    { "lceil",  "⌈" }, { "rceil", "⌉" },
                    { "lfloor", "⌊" }, { "rfloor", "⌋" },
                    -- "lbrace", "rbrace",
                    -- "lmoustache", "rmoustache",
                    { "langle", "⟨" }, { "rangle", "⟩" },
                    -- "lgroup", "rgroup",
                    -- "vert", "Vert",
                    -- "ulcorner", "urcorner",
                    -- "llcorner", "lrcorner",
                    -- "lvert", "rvert", "lVert", "rVert",
                    "backslash",
                    -- "lBrace", "rBrace"
                }
            },
            delimiter_sizing = {
                [false] = {
                    "big", -- "bigl", "bigm", "bigr",
                    "Big", -- "Bigl", "Bigm", "Bigr",
                    "bigg", -- "biggl", "biggm", "biggr",
                    "Bigg", -- "Biggl", "Biggm", "Biggr",
                    "left", "middle", "right"
                },
            },
            greek_letters = {
                [false] = {
                    { "Alpha",      "Α" },
                    { "Beta",       "Β" },
                    { "Gamma",      "Γ" },
                    { "Delta",      "Δ" },
                    { "Epsilon",    "Ε" },
                    { "Zeta",       "Ζ" },
                    { "Eta",        "Η" },
                    { "Theta",      "Θ" },
                    { "Iota",       "Ι" },
                    { "Kappa",      "Κ" },
                    { "Lambda",     "Λ" },
                    { "Mu",         "Μ" },
                    { "Nu",         "Ν" },
                    { "Xi",         "Ξ" },
                    { "Omicron",    "Ο" },
                    { "Pi",         "Π" },
                    { "Rho",        "Ρ" },
                    { "Sigma",      "Σ" },
                    { "Tau",        "Τ" },
                    { "Upsilon",    "Υ" },
                    { "Phi",        "Φ" },
                    { "Chi",        "Χ" },
                    { "Psi",        "Ψ" },
                    { "Omega",      "Ω" },
                    { "varGamma",   "Γ" },
                    { "varDelta",   "∆" },
                    { "varTheta",   "Θ" },
                    { "varLambda",  "Λ" },
                    { "varXi",      "Ξ" },
                    { "varPi",      "Π" },
                    { "varSigma",   "Σ" },
                    { "varUpsilon", "Υ" },
                    { "varPhi",     "Φ" },
                    { "varPsi",     "Ψ" },
                    { "varOmega",   "Ω" },
                    { "alpha",      "α" },
                    { "beta",       "β" },
                    { "gamma",      "γ" },
                    { "delta",      "δ" },
                    { "epsilon",    "𝝐" },
                    { "zeta",       "ζ" },
                    { "eta",        "η" },
                    { "theta",      "θ" },
                    { "iota",       "ι" },
                    { "kappa",      "κ" },
                    { "lambda",     "λ" },
                    { "mu",         "μ" },
                    { "nu",         "ν" },
                    { "xi",         "ξ" },
                    { "omicron",    "ο" },
                    { "pi",         "π" },
                    { "rho",        "ρ" },
                    { "sigma",      "σ" },
                    { "tau",        "τ" },
                    { "upsilon",    "υ" },
                    { "phi",        "φ" },
                    { "chi",        "χ" },
                    { "psi",        "𝝍" },
                    { "omega",      "ω" },
                    { "varepsilon", "ε" },
                    { "varkappa",   "Ϟ" },
                    { "vartheta",   "ϑ" },
                    { "varpi",      "ϖ" },
                    { "varrho",     "𝝔" },
                    { "varsigma",   "ς" },
                    { "varphi",     "𝝋" },
                    { "digamma",    "ϝ" }
                }
            },
            other_letters = {
                [false] = {
                    "imath", "jmath",
                    "Im", "Re",
                    { "nabla", "∇" },
                    { "partial", "∂" }, -- "wp",
                    { "aleph", "א" }, -- "Game", "Bbbk",
                    { "hbar", "ħ" }, -- { "hslash", "ħ" },
                    { "N", "ℕ", "NN" }, { "Z", "ℤ", "ZZ" }, { "Q", "ℚ", "QQ" }, { "R", "ℝ", "RR" },
                    -- "Finv",
                    -- "beth", "gimel", "ell",
                    -- "daleth", "eth",
                }
            },
            vertical_layout = { [false] = { { "atop", "Character above character" } } },
            spacing = {
                [false] = {
                    "thickspace", -- "thinspace", "medspace",
                    "qquad", -- "negthinspace", "negmedspace",
                    -- "nobreakspace", "negthickspace", "space", "mathstrut"
                },
                [true] = { "enspace", "quad" }
            },
            logic_and_set_theory = {
                [false] = {
                    { "complement", "∁" },
                    { "therefore",  "∴" },
                    { "because",    "∵" },
                    { "emptyset",   "∅" },
                    -- { "empty",      "∅" },
                    -- { "varnothing", "∅" },
                    { "subset",     "⊂" },
                    { "supset",     "⊃" },
                    { "mapsto",     "↦", "!>" },
                    { "to",         "→" },
                    { "implies",    "⟹" },
                    { "gets",       "←" },
                    { "impliedby",  "⟸" },
                    { "iff",        "⟺" },
                    { "land",       "∧" },
                    { "lor",        "∨" },
                    { "nexists",    "∄" },
                    { "in",         "∈", "inn" },
                    { "notin",      "∉" },
                    { "ni",         "∋" },
                    { "neg",        "¬" },
                    { "lnot",       "¬" }
                },
                [true] = { { "forall", "∀", "AA" }, { "exists", "∃", "EE" } }
            },
            -- macros = {
            --     [false] = {
            --         "def",                        -- "gdef", "edef", "xdef",
            --         "let",                        -- "futurelet", "global",
            --         "newcommand", "renewcommand", -- "providecommand",
            --         -- "long", "char", "mathchoice", "TextOrMath",
            --         -- "@ifstar", "@ifnextchar", "@firstoftwo", "@secondoftwo",
            --         -- "relax", "expandafter", "noexpand"
            --     }
            -- },
            big_operators = {
                [false] = {
                    -- { "bigotimes", "⨂" },
                    -- { "bigoplus",  "⨁" },
                    -- { "bigodot",   "⨀" },
                    { "bigvee",    "⋁" },
                    { "bigwedge",  "⋀" },
                    -- { "coprod",    "∐" },
                    -- { "biguplus",  "⨄" },
                    -- { "bigsqcup",  "⨆" },
                    -- "smallint",
                    -- "intop",
                    { "iint",   "∬" },
                    { "iiint",  "∭" },
                    { "oint",   "∮" },
                    { "oiint",  "∯" },
                    { "oiiint", "∰" },
                },
            },
            binary_operators = {
                [false] = {
                    { "pmod",            "(mod N)" },
                    { "mod",             "mod N" },
                    -- { "bmod",            "mod" },
                    -- { "pod",             "(N)" },
                    { "cdot",            "⋅",         "**" },
                    -- { "cdotp",           "∙" },
                    -- { "bullet",          "∙ (bigger)" },
                    -- { "centerdot",       "⋅ (square)" },
                    -- { "intercal",        "⊺" },
                    -- { "leftthreetimes",  "⋋" },
                    -- { "rightthreetimes", "⋌" },
                    -- { "amalg",           "⨿" },
                    { "setminus",        "∖" },
                    -- { "smallsetminus",   "∖" },
                    -- { "wedge",           "∧" },
                    -- { "vee",             "∨" },
                    -- { "barwedge",        "⌅" },
                    -- { "veebar",          "⊻" },
                    -- { "doublebarwedge",  "⩞" },
                    -- { "curlywedge",      "⋏" },
                    -- { "curlyvee",        "⋎" },
                    -- { "lhd",             "⊲" },
                    -- { "rhd",             "⊳" },
                    -- { "unlhd",           "⊴" },
                    -- { "unrhd",           "⊵" },
                    -- { "lessdot",         "⋖" },
                    -- { "gtrdot",          "⋗" },
                    -- { "dotplus",         "∔" },
                    { "pm",              "±",          "+-" },
                    { "mp",              "∓",         "-+" },
                    -- { "div",             "÷" },
                    -- { "ast",             "∗" },
                    { "times",           "×" },
                    -- { "ltimes",          "⋉" },
                    -- { "rtimes",          "⋊" },
                    -- { "divideontimes",   "⋇" },
                    -- { "circ",            "∘" },
                    -- { "bigcirc",         "◯" },
                    -- { "circledcirc",     "⊚" },
                    -- { "circleddash",     "⊝" },
                    -- { "circledast",      "⊛" },
                    -- { "oslash",          "⊘" },
                    { "odot",            "⊙" },
                    { "oplus",           "⊕" },
                    -- { "ominus",          "⊖" },
                    -- { "otimes",          "⊗" },
                    -- { "boxdot",          "⊡" },
                    -- { "boxplus",         "⊞" },
                    -- { "boxminus",        "⊟" },
                    -- { "boxtimes",        "⊠" },
                    { "cap",             "∩" },
                    { "cup",             "∪" },
                    -- { "sqcap",           "⊓" },
                    -- { "sqcup",           "⊔" },
                    -- { "uplus",           "⊎" },
                    -- { "Cap",             "⋒" },
                    -- { "Cup",             "⋓" },
                    -- { "wr",              "≀" }
                },
            },
            -- fractions = { [false] = { "over", "above" } },
            binomial_coefficients = { [false] = { "choose" } },
            relations = {
                [false] = {
                    -- { "sqsubset",        "⊏" },
                    -- { "sqsupset",        "⊐" },
                    -- { "sqsubseteq",      "⊑" },
                    -- { "sqsupseteq",      "⊒" },
                    { "subseteq",        "⊆" },
                    { "supseteq",        "⊇" },
                    { "subseteqq",       "⫅" },
                    { "supseteqq",       "⫆" },
                    -- { "Subset",          "⋐" },
                    -- { "Supset",          "⋑" },
                    { "ll",              "<<",  true },
                    { "gg",              ">>",  true },
                    { "lll",             "<<<" },
                    { "ggg",             ">>>" },
                    -- { "leqslant",        "⩽" },
                    -- { "geqslant",        "⩾" },
                    -- { "eqslantless",     "⪕" },
                    -- { "eqslantgtr",      "⪖" },
                    -- { "leqq",            "≦" },
                    -- { "geqq",            "≧" },
                    -- { "lesssim",         "≲" },
                    -- { "gtrsim",          "≳" },
                    -- { "lessapprox",      "⪅" },
                    -- { "gtrapprox",       "⪆" },
                    -- { "lessgtr",         "≶" },
                    -- { "gtrless",         "≷" },
                    -- { "lesseqgtr",       "⋚" },
                    -- { "gtreqless",       "⋛" },
                    -- { "lesseqqgtr",      "⪋" },
                    -- { "gtreqqless",      "⪌" },
                    { "prec",            "≺" },
                    { "succ",            "≻" },
                    -- { "preccurlyeq",     "≼" },
                    -- { "succcurlyeq",     "≽" },
                    -- { "curlyeqprec",     "⋞" },
                    -- { "curlyeqsucc",     "⋟" },
                    { "preceq",          "⪯" },
                    { "succeq",          "⪰" },
                    -- { "precsim",         "≾" },
                    -- { "succsim",         "≿" },
                    -- { "precapprox",      "⪷" },
                    -- { "succapprox",      "⪸" },
                    -- { "vartriangleleft",  "⊲" },
                    -- { "vartriangleright", "⊳" },
                    -- { "trianglelefteq",  "⊴" },
                    -- { "trianglerighteq", "⊵" },
                    { "not =",           "!=",  true },
                    { "sim",             "∼", "~~" },
                    -- { "backsim",         "∽" },
                    -- { "thicksim",        "~" },
                    -- { "thickapprox",     "≈" },
                    -- { "simeq",           "≃" },
                    -- { "backsimeq",       "⋍" },
                    -- { "eqsim",           "≂" },
                    -- { "cong",            "≅" },
                    -- { "approxeq",        "≊" },
                    -- { "circeq",          "≗" },
                    -- { "triangleq",       "≜" },
                    -- { "eqcirc",          "≖" },
                    -- { "doteq",           "≐" },
                    -- { "Doteq",           "≑" },
                    -- { "fallingdotseq",   "≒" },
                    -- { "risingdotseq",    "≓" },
                    -- { "bumpeq",          "≏" },
                    -- { "Bumpeq",          "≎" },
                    -- { "eqcolon",         "-:" },
                    -- { "coloneq",         ":-" },
                    -- { "Coloneq",         "::-" },
                    -- { "dashv",           "-|" },
                    { "vdash",           "|-" },
                    { "vDash",           "|=" },
                    -- { "models",           "|=" },
                    { "Vdash",           "||-" },
                    -- { "Vvdash",          "|||-" },
                    -- { "between",         "≬" },
                    -- { "bowtie",          "⋈" },
                    -- { "Join",             "⋈" },
                    -- { "owns",             "∋" },
                    { "parallel",        "||" },
                    { "perp",            "⊥" },
                    -- { "pitchfork",       "⋔" },
                    { "propto",          "∝" },
                    -- { "vartriangle",     "△" },
                    -- { "frown",           "⌢" },
                    -- { "smile",           "⌣" },
                    -- { "smallfrown",      "⌢" },
                    -- { "smallsmile",      "⌣" },
                    -- { "asymp",           "≍" },
                    -- { "multimap",        "⊸" },
                    -- "imageof",
                    -- "origof",
                },
                [true] = {
                    { "approx", "≈", "~=" },
                    { "equiv",  "≡", "==" },
                    { "leq",    "<=",  true },
                    { "geq",    ">=",  true },
                }
            },
            negated_relations = {
                [false] = {
                    { "nsubseteq",        "⊈" },
                    { "nsupseteq",        "⊉" },
                    -- { "subsetneq",        "⊊" },
                    -- { "supsetneq",        "⊋" },
                    -- { "varsubsetneq",     "Taller canceled ⊊" },
                    -- { "varsupsetneq",     "Taller canceled ⊋" },
                    -- { "nsubseteqq",       "Canceled ⫅" },
                    -- { "nsupseteqq",       "Canceled ⫆" },
                    -- { "subsetneqq",       "⫋" },
                    -- { "supsetneqq",       "⫌" },
                    -- { "varsubsetneqq",    "Taller canceled ⫋" },
                    -- { "varsupsetneqq",    "Taller canceled ⫌" },
                    -- { "nless",            "≮" },
                    -- { "ngtr",             "≯" },
                    -- { "nleq",             "≰" },
                    -- { "ngeq",             "≱" },
                    -- { "nleqslant",        "Canceled ⩽" },
                    -- { "ngeqslant",        "Canceled ⩾" },
                    -- { "lneq",             "⪇" },
                    -- { "gneq",             "⪈" },
                    -- { "nleqq",            "Canceled ≦" },
                    -- { "ngeqq",            "Canceled ≧" },
                    -- { "lneqq",            "≨" },
                    -- { "gneqq",            "≩" },
                    -- { "lvertneqq",        "Vertical canceled ≨" },
                    -- { "gvertneqq",        "Vertical canceled ≩" },
                    -- { "lnsim",            "⋦" },
                    -- { "gnsim",            "⋧" },
                    -- { "lnapprox",         "⪉" },
                    -- { "gnapprox",         "⪊" },
                    { "nprec",            "⊀" },
                    { "nsucc",            "⊁" },
                    -- { "npreceq",          "⋠" },
                    -- { "nsucceq",          "⋡" },
                    -- { "precneqq",         "⪵" },
                    -- { "succneqq",         "⪶" },
                    -- { "precnsim",         "⋨" },
                    -- { "succnsim",         "⋩" },
                    -- { "precnapprox",      "⪹" },
                    -- { "succnapprox",      "⪺" },
                    -- { "ntriangleleft",    "⋪" },
                    -- { "ntriangleright",   "⋫" },
                    -- { "ntrianglelefteq",  "⋬" },
                    -- { "ntrianglerighteq", "⋭" },
                    -- { "nsim",             "≁" },
                    -- { "ncong",            "≆" },
                    -- { "nvdash",           "⊬" },
                    -- { "nvDash",           "⊭" },
                    -- { "nVdash",           "⊮" },
                    -- { "nVDash",           "⊯" },
                    { "nmid",             "∤" },
                    -- { "nshortmid",        "Smaller ∤" },
                    { "nparallel",        "∦" },
                    -- { "nshortparallel",   "Smaller ∦" },
                }
            },
            arrows = {
                [false] = {
                    { "leftarrow",           "←", "-<" },
                    -- { "nleftarrow",          "↚" },
                    { "longleftarrow",       "<--" },
                    { "rightarrow",          "→", "->" },
                    -- { "nrightarrow",         "↛" },
                    { "longrightarrow",      "-->" },
                    { "longmapsto",          "|-->" },
                    { "leftrightarrow",      "↔" },
                    -- { "nleftrightarrow",     "↮" },
                    { "longleftrightarrow",  "<-->" },
                    -- { "uparrow",             "↑" },
                    -- { "downarrow",           "↓" },
                    -- { "updownarrow",         "↕" },
                    { "Leftarrow",           "⇐", "=<" },
                    -- { "nLeftarrow",          "⇍" },
                    { "Longleftarrow",       "<==" },
                    { "Rightarrow",          "⇒", "=>" },
                    -- { "nRightarrow",         "⇏" },
                    { "Longrightarrow",      "==>" },
                    { "Leftrightarrow",      "⇔", "<>=", priority = 1200 },
                    -- { "nLeftrightarrow",     "⇎" },
                    { "Longleftrightarrow",  "<==>" },
                    -- { "Uparrow",             "⇑" },
                    -- { "Downarrow",           "⇓" },
                    -- { "Updownarrow",         "⇕" },
                    -- { "Lleftarrow",          "⇚" },
                    -- { "Rrightarrow",         "⇛" },
                    -- { "nwarrow",             "↖" },
                    -- { "nearrow",             "↗" },
                    -- { "searrow",             "↘" },
                    -- { "swarrow",             "↙" },
                    -- { "leftarrowtail",       "↢" },
                    -- { "rightarrowtail",      "↣" },
                    -- { "twoheadleftarrow",    "↞" },
                    -- { "twoheadrightarrow",   "↠" },
                    -- { "dashleftarrow",       "⇠" },
                    -- { "dashrightarrow",      "⇢" },
                    -- { "rightsquigarrow",     "⇝" },
                    -- { "leftrightsquigarrow", "↭" },
                    -- { "leftleftarrows",      "⇇" },
                    -- { "rightrightarrows",    "⇉" },
                    -- { "upuparrows",          "⇈" },
                    -- { "downdownarrows",      "⇊" },
                    -- { "leftrightarrows",     "⇆" },
                    -- { "rightleftarrows",     "⇄" },
                    -- { "leftharpoonup",       "↼" },
                    -- { "leftharpoondown",     "↽" },
                    -- { "rightharpoondown",    "⇁" },
                    -- { "rightharpoonup",      "⇀" },
                    -- { "upharpoonleft",       "↿" },
                    -- { "upharpoonright",      "↾" },
                    -- { "downharpoonleft",     "⇃" },
                    -- { "downharpoonright",    "⇂" },
                    -- { "leftrightharpoons",   "⇋" },
                    -- { "rightleftharpoons",   "⇌" },
                    -- { "Lsh",                 "↰" },
                    -- { "Rsh",                 "↱" },
                    -- { "circlearrowleft",     "↺" },
                    -- { "circlearrowright",    "↻" },
                    -- { "curvearrowleft",      "↶" },
                    -- { "curvearrowright",     "↷" },
                    -- { "hookleftarrow",       "↩" },
                    -- { "hookrightarrow",      "↪" },
                    -- { "looparrowleft",       "↫" },
                    -- { "looparrowright",      "↬" },
                },
            },
            font = {
                [false] = {
                    { "rm", "Normal font" },
                    { "bf", "Bold font" },
                    { "it", "Italics font" },
                    { "sf", "Serif font" },
                    { "tt", "Monospace font" },
                }
            },
            size = {
                [false] = {
                    "Huge", "huge", "LARGE", "Large", "large", "normalsize",
                    "small", "footnotesize", "scriptsize", "tiny"
                }
            },
            style = {
                [false] = {
                    { "displaystyle", nil, "ds" },
                    -- "textstyle",
                    -- "scriptstyle",
                    -- "scriptscriptstyle",
                    { "limits",       nil, "lm" },
                    -- "nolimits",
                    -- "verb",
                },
            },
            symbols_and_punctuation = {
                [false] = {
                    -- "LaTeX",
                    -- "TeX",
                    { "ddots",              "⋱" },
                    { "vdots",              "⋮" },
                    { "cdots",              "⋯",    "..." },
                    -- { "ldots",              "⋯" },
                    -- { "diagdown",           "╲" },
                    -- { "diagup",             "╱" },
                    -- { "lq",                 "‘" },
                    -- { "rq",                 "′" },
                    -- { "backprime",          "‵" },
                    -- { "prime",              "′" },
                    { "infty",              "∞",    "inf" },
                    { "top",                "⊤" },
                    { "bot",                "⊥" },
                    { "angle",              "∠" },
                    -- { "measuredangle",      "∡" },
                    -- { "sphericalangle",     "∢" },
                    -- { "surd",               "√" },
                    -- { "checkmark",          "✓" },
                    -- { "pounds",             "£" },
                    -- { "yen",                "¥" },
                    -- { "dagger",             "†" },
                    -- { "ddagger",            "‡" },
                    -- { "square",             "□" },
                    -- { "blacksquare",        "■" },
                    -- { "triangleleft",       "◃" },
                    -- { "blacktriangleleft",  "◀" },
                    -- { "triangleright",      "▹" },
                    -- { "blacktriangleright", "▶" },
                    -- { "triangle",           "△" },
                    -- { "bigtriangleup",      "Big △" },
                    -- { "blacktriangle",      "▲" },
                    -- { "triangledown",       "▽" },
                    -- { "bigtriangledown",    "Big ▽" },
                    -- { "blacktriangledown",  "▼" },
                    -- { "maltese",            "✠" },
                    -- { "star",               "⋆" },
                    -- { "bigstar",            "★" },
                    -- { "diamond",            "⋄" },
                    -- { "Diamond",            "◊" },
                    -- { "blacklozenge",       "⧫" },
                    -- { "diamondsuit",        "♢" },
                    -- { "heartsuit",          "♡" },
                    -- { "clubsuit",           "♣" },
                    -- { "spadesuit",          "♠" },
                    -- { "mho",                "℧" },
                    -- { "flat",               "♭" },
                    -- { "natural",            "♮" },
                    -- { "sharp",              "♯" },
                    -- { "copyright",          "©" },
                    -- { "circledR",           "®" },
                    -- { "circledS",           "Ⓢ" },
                },
            },
            -- debugging = { [false] = { "message", "show" } }
        },
        {
            accents = {
                [false] = {
                    -- { "tilde",               "ã" },
                    -- { "widetilde",           "Extensible ã" },
                    -- { "mathring",            "å" },
                    { "dot",                 "ȧ" },
                    { "ddot",                "ä" },
                    -- { "acute",               "á" },
                    -- { "grave",               "à" },
                    -- { "breve",               "ă" },
                    -- { "check",               "ǎ" },
                    -- { "widecheck",           "Extensible ǎ" },
                    { "hat",                 "â",            "hat" },
                    { "widehat",             "Extensible â" },
                    -- { "bar",                 "Thin ā" },
                    { "overline",            "ā",            "bar" },
                    -- { "underbar",            "Bottom thin ā" },
                    -- { "underline",           "Bottom ā" },
                    { "vec",                 "Thin a⃗",     "vec" },
                    -- { "overleftarrow",       "a⃖" },
                    -- { "overrightarrow",      "a⃗" },
                    -- { "overleftrightarrow",  "a⃡" },
                    -- { "overleftharpoon",     "a⃐" },
                    -- { "overrightharpoon",    "a⃑" },
                    -- { "underleftarrow",      "" },
                    -- { "underrightarrow",     "" },
                    -- { "underleftrightarrow", "Bottom a⃡" },
                }
            },
            annotation = {
                [false] = {
                    { "overbrace",  "Top }" },
                    { "underbrace", "Bottom }" },
                    -- { "boxed",      "Rectangle around contents" },
                    -- {"tag", ""},
                }
            },
            vertical_layout = { [false] = { { "substack", "Multiline content" } } },
            -- overlap = { [false] = { "llap", "rlap", "clap", "smash" } },
            spacing = {
                -- [false] = { --[["kern", "mkern", "mskip", "hskip", "hspace*",]] "phantom", "hphantom", "vphantom" },
                [true] = { { "hspace", "Horizontal space" }, { "vspace", "Vertical space" } },
            },
            math_operators = { [false] = { "operatorname", "operatorname*", "operatornamewithlimits" } },
            sqrt = { [true] = { { "sqrt", "√" } } },
            extensible_arrows = { [false] = { { "xleftarrow", "Extensible <-" }, { "xrightarrow", "Extensible ->" } } },
            -- class_assignment = {
            --     [false] = { "mathbin", "mathclose", "mathinner", "mathop", "mathopen", "mathord", "mathpunct", "mathrel" }
            -- },
            font = {
                [false] = {
                    { "textbf",     "Bold font" },
                    { "textit",     "Italics font" },
                    { "textrm",     "Normal font" },
                    -- { "textsf",     "Serif font" },
                    { "texttt",     "Monospace font" },
                    { "textnormal", "Normal text font" },
                    { "boldsymbol", "Bold math font" },
                    { "mathbb",     "Blackboard bold font" },
                    { "mathfrak",   "Fraktur font" },
                    { "mathcal",    "Calligraphic font" },
                    { "mathscr",    "Script font" },
                    -- "pmb",
                },
                [true] = { { "text", "Text mode", "txt" } }
            }
        },
        {
            vertical_layout = {
                [false] = {
                    -- { "stackrel", "Character above character" },
                    { "overset",  "Character above character" },
                    { "underset", "Character below character" },
                    { "raisebox", "Move character upwards" },
                }
            },
            fractions = {
                -- [false] = {
                --     { "dfrac", "Display style fraction" },
                --     { "tfrac", "Inline style fraction" },
                --     { "cfrac", "Continued fraction" },
                --     -- "genfrac"
                -- },
                [true] = { { "frac", "Fraction" } },
            },
            binomial_coefficients = {
                [false] = {
                    { "binom",  "Binomial coefficient" },
                    -- { "dbinom", "Display style binomial coefficient" },
                    -- { "tbinom", "Inline style binomial coefficient" },
                    -- { "brace",  "Binomial coefficient with }" },
                    -- { "brack",  "Binomial coefficient with ]" },
                }
            },
            -- color = {
            --     [false] = { { "color", "Color text" }, { "textcolor", "Color text" }, { "colorbox", "Color background" } }
            -- }
        },
    },
    -- Table with function commands
    ---@type SnippetGroup
    functions = {
        [false] = {
            "deg", "sec",
            "cosh", "dim",
            "cot", "sinh",
            -- "hom",
            "coth", "ker",
            "arg", "csc", "lg", "tanh",
            -- "th",
            -- "injlim", "varinjlim",
            -- "varliminf",
            "inf",
            "sup",
            "det", -- "liminf", "Pr", "varlimsup",
            "gcd", -- "limsup", "projlim", "varprojlim",
        },
        [true] = {
            "arcsin", "arccos", "arctan",
            "sin", "cos", "tan",
            "exp", "log", "ln",
            "min", "max",
        }
    },
    -- Table with the operators using subscript/superscrip limits
    ---@type SnippetGroup
    limit_operators = {
        [false] = {
            { "bigcap", "⋂" },
            { "bigcup", "⋃" },
        },
        [true] = {
            { "sum",  "∑" },
            { "prod", "∏" },
        },
    },
    ---@type SnippetSpec
    int = { "int", "∫" },
    ---@type SnippetSpec
    limit = { "lim", "Limit" },
    -- Table with the math environments
    envs = {
        "aligned",
        "alignedat",
        "matrix",
        "pmatrix",
        "bmatrix",
        "vmatrix",
        "Vmatrix",
        "Bmatrix",
        "cases",
        "rcases",
    },
    ---@type AutoSnippetSpecs
    txt_autosnippets = {
        sr = { "^2", "²" },
        cb = { "^3", "³" },
        inv = { "^{-1}", "⁻¹" },
    },
    ---@type AutoSnippetSpecs
    postfix_autosnippets = {
        hat = { "hat", "Hat" },
        bar = { "overline", "Bar" },
        vec = { "vec", "Vector" },
    }
}
